sudo: required

language: java
dist: trusty

jdk:
- openjdk8

services:
  - docker

before_install:
  - docker build -t rsodocker123:account-service .
  - docker run -d -p 127.0.0.1:8080:4567 rsodocker123:account-service /bin/sh -c "cd /root; bundle exec foreman start;"
  - docker ps -a
  - docker run rsodocker123:account-service /bin/sh -c "cd /root;"
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag rsodocker123:account-service rsodocker123/account-service:qwe
    docker push rsodocker123/account-service:qwe;
    fi