apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    qwe: account-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    qwe: account-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        qwe: account-service
    spec:
      containers:
      - image: rsodocker123/account-service
        imagePullPolicy: Always
        name: account-service
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: etcd-cluster
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 443
        - containerPort: 8081
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always