apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:1.0.0
        ports:
        - containerPort: 80