kumuluzee:
  name: account-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    etcd:
      hosts: http://localhost:2379
rest-properties:
  external-dependencies:
    account-service:
      registration-enabled: true